"""
    RhsStokesArray1D

Module containing 1D arrays for the right-hand side of Stokes equations in the
EarthBox model. These arrays store the right-hand side vector of the system of
equations generated by discretizing the Stokes-continuity equations.
"""
module RhsStokesArray1D

import EarthBox.EarthBoxDtypes: AbstractEarthBoxArray1D

"""
    RhsStokesArray1DState

Struct containing a 1D array for Stokes equation right-hand side.

# Fields
- `array`: the 1D array data
- `name`: name of the array
- `units`: physical units of the array values
- `description`: description of the array's purpose
"""
mutable struct RhsStokesArray1DState <: AbstractEarthBoxArray1D
    array::Vector{Float64}
    name::String
    units::String
    description::String
end

"""
    RhsStokesArray1DState(ynum::Int, xnum::Int, name::String, units::String, description::String)::RhsStokesArray1DState

Construct a new RhsStokesArray1DState with array of appropriate size.

# Arguments
- `ynum`: number of nodes in y-direction
- `xnum`: number of nodes in x-direction
- `name`: name of the array
- `units`: physical units of the array values
- `description`: description of the array's purpose

# Returns
A new RhsStokesArray1DState with initialized array:
- Array initialized to zero
- Appropriate metadata set
"""
function RhsStokesArray1DState(
    ynum::Int,
    xnum::Int,
    name::String,
    units::String,
    description::String
)::RhsStokesArray1DState
    array = zeros(Float64, (xnum-1)*(ynum-1)*3)
    return RhsStokesArray1DState(array, name, units, description)
end

end # module 