module MultigridManager

include("utils/ScalingFactors.jl")
include("utils/Domain.jl")
include("utils/NormalizeCoordinates.jl")
include("grid_mapping/GridMappingManager.jl")
include("level_manager/LevelManager.jl")
include("utils/CalculateMeanResiduals.jl")
include("multigrid_data/MultigridDataManager.jl")
include("utils/ArrayStats.jl")
include("boundary_conditions/BoundaryConditions.jl")
include("interpolation/WeightFuncs3d.jl")
include("interpolation/WeightFuncs2d.jl")
include("interpolation/TriLinearInterpolation.jl")
include("interpolation/BiLinearInterpolation.jl")
include("interpolation/ViscosityRestriction.jl")
include("interpolation/LevelInterpolation.jl")
include("prolongation/Prolongation.jl")
include("smoother/Smoother.jl")
include("restriction/Restriction.jl")
include("plot_tools/ResidualPlotting.jl")
include("plot_tools/ResidualPlottingCM.jl")
include("viscosity_scaling/ViscosityScaling.jl")
include("vcycle/MultigridVCycle.jl")
include("multigrid_solver/MultigridSolver.jl")
include("multigrid_tests/MultigridTests.jl")

end