include("PrintInflowOutflow.jl")
include("SetParameters.jl")
include("SolveForVelocity.jl")
include("UpperAndLowerVelocity.jl")
include("AverageVelocity.jl")
include("VelocityFactors.jl")
include("StickyThickness.jl")
# The following modules have local dependencies
include("GetInputs.jl")
include("OutflowGeometry.jl")
include("InflowGeometry.jl")
include("InflowRamp.jl")
include("UniformSideVelocity.jl")
include("DepthDependentSideVelocity.jl")
include("ConservationCheck.jl")